version: '3'
services:
  nginx:
    container_name: ltb_server-nginx
    image: ltb_server-nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media
    depends_on:
      - web

  web:
    container_name: ltb_server-core
    image: ltb_server-core:latest
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    container_name: ltb_server-database
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume:
  media_volume: