version: '3'
services:
  nginx:
    build: ./config/nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media
    depends_on:
      - web

  web:
    build: .
    volumes:
      - static_volume:/src/static
      - media_volume:/src/media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume:
  media_volume: