# Generated by Django 3.2.9 on 2021-12-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTBEditionNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Edition number')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LTBNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Number')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='LTBType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('auto_url', models.BooleanField(verbose_name='Set number url')),
                ('type_url', models.CharField(blank=True, default='/ausgaben/alle-ausgaben', max_length=255, null=True, verbose_name='Type Url')),
                ('current_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Current Number')),
                ('auto_fetch', models.BooleanField(verbose_name='Auto fetch books')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['code'],
                'permissions': [('fetch_new_books', 'Can fetch new books')],
            },
        ),
        migrations.CreateModel(
            name='LTBNumberSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('ltb_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='ltb.ltbnumber')),
                ('ltb_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='ltb.ltbtype')),
            ],
            options={
                'ordering': ['ltb_number'],
                'unique_together': {('ltb_type', 'ltb_number')},
            },
        ),
        migrations.CreateModel(
            name='LTBEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('url', models.CharField(max_length=255, verbose_name='Url')),
                ('stories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stories')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pages')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('ltb_edition_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='ltb.ltbeditionnumber')),
                ('ltb_number_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='ltb.ltbnumberset')),
            ],
            options={
                'ordering': ['ltb_number_set', 'ltb_edition_number'],
                'unique_together': {('ltb_number_set', 'ltb_edition_number')},
            },
        ),
        migrations.CreateModel(
            name='LTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('complete_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complete Name')),
                ('sort', models.PositiveIntegerField(verbose_name='Sort')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image Url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='Image')),
                ('is_read', models.BooleanField(verbose_name='Gelesen')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('ltb_edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ltbs', to='ltb.ltbedition')),
            ],
            options={
                'ordering': ['ltb_edition__ltb_number_set__ltb_type', 'ltb_edition__ltb_number_set__ltb_number', 'ltb_edition__ltb_edition_number', 'sort'],
                'unique_together': {('ltb_edition', 'sort')},
            },
        ),
    ]
