name: create_and_push_image

on:
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/ltb_server-core:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/ltb_server-core:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ltb_server-core:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/ltb_server-core:buildcache,mode=max